name: Producer Workflow

on:
  push:
    paths:
      - 'RedditProducer.py'
    branches:
      - '*'
  pull_request:
    paths:
      - 'RedditProducer.py'
    branches:
      - '*'

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install EditorConfig Checker
        run: pip install editorconfig-checker
      - name: Run Editorconfig
        run: editorconfig-checker

  linter:
    runs-on: ubuntu-latest
    needs: editorconfig
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Linter Check
        run: pip install pylint
             pylint RedditProducer.py

  azure:
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        run: az login

      - name: Build Docker Image
        run: docker build -t redditproducer -f Dockerfile.Producer .

      - name: Save Docker Image
        run: docker save -o redditproducer.tar redditproducer

      - name: Push Producer Image to ACR
        run: az acr login --name dataredditegistry
             docker tag redditproducer dataredditegistry.azurecr.io/producer:latest
             docker push dataredditegistry.azurecr.io/producer:latest
             
      - name: Push Producer Image to container app
        run: az container restart --resource-group TPIUO-labosi --name producer-ca --image dataredditegistry.azurecr.io/producer:latest --registry-login-server dataredditegistry.azurecr.io --registry-username dataredditegistry --registry-password cBrKg4IWiQ4k4spbUF3XeyFxEmmddbRmqkDMfMjAIp+ACRBl/Utz

      

